using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace SourceGeneration.States.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public partial class ChanageTrackingProxySourceGenerator : IIncrementalGenerator
{
    public const string RootNamespace = "SourceGeneration.States";

    public const string ChangeTrackingAttribute = $"{RootNamespace}.ChangeTrackingAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            ChangeTrackingAttribute,
            predicate: static (node, token) =>
            {
                if (node is not TypeDeclarationSyntax type
                    //|| !type.IsPartial()
                    || type.IsAbstract()
                    || type.TypeParameterList != null)
                {
                    return false;
                }

                if (!type.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.ClassDeclaration) &&
                    !type.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.RecordDeclaration))
                {
                    return false;
                }

                //如果是内部类，需要确保父级都是 class，record 且为 partial
                //var parent = type.Parent;
                //while (parent != null)
                //{
                //    if (parent is BaseNamespaceDeclarationSyntax or CompilationUnitSyntax)
                //        break;

                //    if (parent is not TypeDeclarationSyntax tp)
                //        return false;

                //    if (!tp.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.ClassDeclaration) &&
                //        !tp.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.RecordDeclaration))
                //    {
                //        return false;
                //    }

                //    if (!tp.IsPartial() || tp.TypeParameterList != null)
                //        return false;

                //    parent = parent.Parent;
                //}

                return true;
            },
            transform: static (context, token) =>
            {
                return (TypeDeclarationSyntax)context.TargetNode;
            });

        var source = methodDeclarations.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(source, static (sourceContext, source) =>
        {
            CancellationToken cancellationToken = sourceContext.CancellationToken;
            TypeDeclarationSyntax type = source.Left;
            Compilation compilation = source.Right;

            SemanticModel model = compilation.GetSemanticModel(type.SyntaxTree);
            var typeSymbol = (INamedTypeSymbol)model.GetDeclaredSymbol(type, cancellationToken)!;

            var typeProxy = CreateProxy(typeSymbol, cancellationToken);

            //if (typeProxy.Properties.Count == 0)
            //    return;

            var root = (CompilationUnitSyntax)type.SyntaxTree.GetRoot();

            CSharpCodeBuilder builder = new();
            builder.AppendAutoGeneratedComment();

            if (typeProxy.Namespace == null)
            {
                CreateSource(typeSymbol.GetFullName(), typeProxy, builder);
            }
            else
            {
                builder.AppendBlock($"namespace {typeProxy.Namespace}", () =>
                {
                    CreateSource(typeSymbol.GetFullName(), typeProxy, builder);
                });
            }

            var code = builder.ToString();
            sourceContext.AddSource($"{typeSymbol.GetFullName(false)}.ChangeTackingProxy.g.cs", code);
        });
    }

    private static void CreateSource(string typeFullName, TypeDefinition typeProxy, CSharpCodeBuilder builder)
    {
        var typekind = typeProxy.IsRecord ? "record" : "class";

        builder.AppendBlock($"internal partial {typekind} {typeProxy.Name}__Proxy__ : {typeFullName}, global::{RootNamespace}.ICascadingChangeTracking, global::System.ComponentModel.INotifyPropertyChanged", () =>
        {
            builder.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.AppendBlock("public static void __Initialize()", () =>
            {
                var requires = typeProxy.Properties.Where(x => x.Required).Select(x => $"{x.PropertyName} = x.{x.PropertyName}").ToList();
                if (requires.Count > 0)
                {
                    string initProperties = "{ " + string.Join(", ", requires) + " }";
                    builder.AppendLine($"global::{RootNamespace}.ChangeTrackingProxyFactory.Register<{typeFullName}>(x => new {typeProxy.Name}__Proxy__(x) {initProperties} );");
                }
                else
                {
                    builder.AppendLine($"global::{RootNamespace}.ChangeTrackingProxyFactory.Register<{typeFullName}>(x => new {typeProxy.Name}__Proxy__(x));");
                }
            });
            builder.AppendLine();

            builder.AppendLine("private bool __cascadingChanged;");
            builder.AppendLine("private bool __baseChanged;");
            builder.AppendLine();

            builder.AppendLine("public bool IsChanged => __baseChanged || __cascadingChanged;");
            builder.AppendLine("public bool IsCascadingChanged => __cascadingChanged;");
            builder.AppendLine("public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;");
            builder.AppendLine("public event global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged;");
            builder.AppendLine();

            builder.AppendBlock($"public {typeProxy.Name}__Proxy__({typeFullName} source)", () =>
            {
                foreach (var property in typeProxy.Properties.Where(x => !x.Required))
                {
                    builder.AppendLine($"this.{property.PropertyName} = source.{property.PropertyName};");
                }
            });
            builder.AppendLine();

            builder.AppendBlock("private void OnPropertyChanged(string propertyName)", () =>
            {
                builder.AppendLine("this.__baseChanged = true;");
                builder.AppendLine("this.PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");
            });
            builder.AppendLine();
            builder.AppendBlock("private void OnPropertyChanged(object sender, global::System.ComponentModel.PropertyChangedEventArgs e)", () =>
            {
                builder.AppendLine("this.__cascadingChanged = true;");
                builder.AppendLine("this.PropertyChanged?.Invoke(sender, e);");
            });
            builder.AppendLine();
            builder.AppendBlock("private void OnCollectionChanged(object sender, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)", () =>
            {
                builder.AppendLine("this.__cascadingChanged = true;");
                builder.AppendLine("CollectionChanged?.Invoke(sender, e);");
            });
            builder.AppendLine();

            builder.AppendBlock($"public void AcceptChanges()", () =>
            {
                builder.AppendLine("this.__baseChanged = false;");
                builder.AppendBlock("if (__cascadingChanged)", () =>
                {
                    builder.AppendLine("this.__cascadingChanged = false;");
                    foreach (var property in typeProxy.Properties.Where(x => x.ChangeTracking))
                    {
                        builder.AppendLine($"((global::System.ComponentModel.IChangeTracking)this.{property.PropertyName})?.AcceptChanges();");
                    }
                });
            });
            builder.AppendLine();

            foreach (var property in typeProxy.Properties.Where(x => x.IsVirtual))
            {
                var required = property.Required ? "required " : string.Empty;
                builder.AppendBlock($"public override {required}{property.Type} {property.PropertyName}", () =>
                {
                    builder.AppendLine($"get => base.{property.PropertyName};");

                    builder.AppendBlock("set", () =>
                    {
                        builder.AppendBlock($"if (!global::System.Collections.Generic.EqualityComparer<{property.Type}>.Default.Equals(base.{property.PropertyName}, value))", () =>
                        {
                            if (property.Kind == TypeProxyKind.Value)
                            {
                                builder.AppendLine($"base.{property.PropertyName} = value;");
                            }
                            else
                            {
                                builder.AppendBlock($"if (base.{property.PropertyName} is not null)", () =>
                                {
                                    if (property.NotifyPropertyChanged)
                                    {
                                        builder.AppendBlock($"if (base.{property.PropertyName} is global::System.ComponentModel.INotifyPropertyChanged)", () =>
                                        {
                                            builder.AppendLine($"((global::System.ComponentModel.INotifyPropertyChanged)base.{property.PropertyName}).PropertyChanged -= OnPropertyChanged;");
                                        });
                                    }
                                    if (property.NotifyCollectionChanged)
                                    {
                                        builder.AppendLine($"((global::System.Collections.Specialized.INotifyCollectionChanged)base.{property.PropertyName}).CollectionChanged -= OnCollectionChanged;");
                                    }
                                });
                                builder.AppendLine();
                                builder.AppendBlock("if (value is null)", () =>
                                {
                                    builder.AppendLine($"base.{property.PropertyName} = null;");
                                });
                                builder.AppendBlock("else", () =>
                                {
                                    if (property.Kind == TypeProxyKind.Collection)
                                    {
                                        builder.AppendLine($"base.{property.PropertyName} = new global::{RootNamespace}.ChangeTrackingList<{property.ElementType}>(value);");
                                    }
                                    else if (property.Kind == TypeProxyKind.Dictionary)
                                    {
                                        builder.AppendLine($"base.{property.PropertyName} = new global::{RootNamespace}.ChangeTrackingDictionary<{property.KeyType}, {property.ElementType}>(value);");
                                    }
                                    else
                                    {
                                        builder.AppendLine($"base.{property.PropertyName} = global::{RootNamespace}.ChangeTrackingProxyFactory.Create(value);");
                                    }

                                    if (property.NotifyPropertyChanged)
                                    {
                                        builder.AppendLine($"((global::System.ComponentModel.INotifyPropertyChanged)base.{property.PropertyName}).PropertyChanged += OnPropertyChanged;");
                                    }
                                    if (property.NotifyCollectionChanged)
                                    {
                                        builder.AppendLine($"((global::System.Collections.Specialized.INotifyCollectionChanged)base.{property.PropertyName}).CollectionChanged += OnCollectionChanged;");
                                    }
                                });
                                builder.AppendLine();
                            }
                            builder.AppendLine($"this.OnPropertyChanged(\"{property.PropertyName}\");");
                        });
                    });
                });
                builder.AppendLine();
            }
        });
    }

    private static TypeDefinition CreateProxy(INamedTypeSymbol type, CancellationToken cancellationToken)
    {
        var properties = type.GetMembers().OfType<IPropertySymbol>().Where(x => !x.IsReadOnly && !x.IsStatic && !x.IsWriteOnly);

        TypeDefinition typeProxy = new(type.Name, type.GetNamespace(), type.IsRecord);

        foreach (var field in properties)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (field.Type is not INamedTypeSymbol propertyType)
                continue;

            var property = CreateProperty(field);
            if (property != null)
            {
                typeProxy.Properties.Add(property);
            }
        }

        return typeProxy;


        static PropertyDefinition? CreateProperty(IPropertySymbol property)
        {
            var type = property.Type;
            var typeName = property.Type.GetFullName();
            var propertyName = property.Name;

            if (type.IsValueType ||
                type.TypeKind == TypeKind.Struct ||
                type.TypeKind == TypeKind.Enum ||
                type.IsTupleType ||
                typeName == "string")
            {
                return new PropertyDefinition(TypeProxyKind.Value, propertyName, typeName, property.IsVirtual, property.IsRequired);
            }

            if (type is INamedTypeSymbol namedType && namedType.IsGenericType)
            {
                var definition = type.OriginalDefinition.GetFullName();

                if (definition == "global::System.Collections.Generic.IDictionary<T,K>")
                {
                    return new PropertyDefinition(TypeProxyKind.Dictionary, propertyName, typeName, property.IsVirtual, property.IsRequired)
                    {
                        KeyType = namedType.TypeArguments[0].GetFullName(),
                        ElementType = namedType.TypeArguments[1].GetFullName(),
                        NotifyCollectionChanged = true,
                        NotifyPropertyChanged = true,
                        ChangeTracking = true,
                    };
                }
                else if (definition == "global::System.Collections.Generic.IList<T>")
                {
                    return new PropertyDefinition(TypeProxyKind.Collection, propertyName, typeName, property.IsVirtual, property.IsRequired)
                    {
                        ElementType = namedType.TypeArguments[0].GetFullName(),
                        NotifyCollectionChanged = true,
                        NotifyPropertyChanged = true,
                        ChangeTracking = true,
                    };
                }
            }

            bool notifyPropertyChanged = false;
            bool notifyCollectionChanged = false;
            bool changeTracking = false;

            foreach (var @interface in type.AllInterfaces)
            {
                var fullName = @interface.GetFullName();

                if (fullName == "global::System.ComponentModel.INotifyPropertyChanged")
                {
                    notifyPropertyChanged = true;
                }
                else if (fullName == "global::System.Collections.Specialized.INotifyCollectionChanged")
                {
                    notifyCollectionChanged = true;
                }
                else if (fullName == "global::System.ComponentModel.IChangeTracking")
                {
                    changeTracking = true;
                }

                if (notifyPropertyChanged && notifyCollectionChanged)
                    break;
            }

            var proxiable = type.HasAttribute(ChangeTrackingAttribute);

            return new PropertyDefinition(TypeProxyKind.Object, propertyName, typeName, property.IsVirtual, property.IsRequired)
            {
                NotifyCollectionChanged = notifyCollectionChanged,
                NotifyPropertyChanged = notifyPropertyChanged || proxiable,
                ChangeTracking = changeTracking || proxiable,
            };
        }
    }

    private sealed class TypeDefinition(string name, string? ns, bool isRecord)
    {
        public readonly string? Namespace = ns;
        public readonly string Name = name;
        public readonly bool IsRecord = isRecord;

        public readonly List<PropertyDefinition> Properties = [];
    }

    private sealed class PropertyDefinition(TypeProxyKind proxyKind, string propertyName, string type, bool isVirtual, bool required)
    {
        public readonly string PropertyName = propertyName;
        public readonly string Type = type;
        public readonly TypeProxyKind Kind = proxyKind;
        public readonly bool Required = required;
        public readonly bool IsVirtual = isVirtual;

        public string? KeyType;
        public string? ElementType;

        public bool NotifyPropertyChanged;
        public bool NotifyCollectionChanged;
        public bool ChangeTracking;

    }

    private enum TypeProxyKind
    {
        Value,
        Object,
        Collection,
        Dictionary,
    }
}

